version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
    reviewers:
      - "DaniloNR"
    versioning-strategy: "widen"
    actions:
      - type: "run_workflow"
        workflow: "run-unit-tests"
      - type: "run_workflow"
        workflow: "run-e2e-tests"
